# Generated by Django 6.1.1 on 2026-10-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_insurance_insuranceclaim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='net_salary',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10),
        ),
    ]
